---
- name: Setup macOS
  hosts: localhost
  connection: local

  roles:
    - karabiner
    - google-japanese-ime
    - raycast
    - mise
    - fish
    - ghostty
    - cmux
    - alt-tab
    - obsidian
    - brave-browser
    - claude-desktop
    - claude-code
    - dato
    - google-cloud-sdk
    - codex
    - gh
    - gemini-cli
    - stow
    - mas
    - googleworkspace-cli
    - google-chrome
    - slack
    - google-drive
    - notchnook
