---
- name: Ensure git is available
  command: git --version
  changed_when: false

- name: Check if Karabiner-Elements is already installed
  stat:
    path: /Applications/Karabiner-Elements.app
  register: karabiner_app

- name: Install Karabiner-Elements
  community.general.homebrew_cask:
    name: karabiner-elements
    state: present
    sudo_password: "{{ ansible_become_password | default(omit) }}"
  when: not karabiner_app.stat.exists

