---
- name: Check if Tailscale is already installed
  stat:
    path: /Applications/Tailscale.app
  register: tailscale_installed

- name: Install Tailscale
  community.general.homebrew_cask:
    name: tailscale-app
    state: present
    sudo_password: "{{ ansible_become_password | default(omit) }}"
  when: not tailscale_installed.stat.exists
