---
- name: Install Google Workspace CLI
  community.general.homebrew:
    name: googleworkspace-cli
    state: present
  ignore_errors: true
  register: gws_install

- name: Force link Google Workspace CLI
  command: brew link --overwrite googleworkspace-cli
  when: gws_install is failed
